version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: shivkumar@12345
      MYSQL_DATABASE: RoomRadar
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: roomradar-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data:
